BASE_DIR=../..

# Include files
INCLUDE +=-I./include -I$(BASE_DIR)/common/include

# Library filenames, _MT for multi-threaded version
LIBNAME=search

TEST_SUBDIRS = testcases # testcases_mt

include $(BASE_DIR)/build/Makefile.inc
