BASE_DIR=../../..

#TEST_SUBDIRS = testcases 

# Include files
INCLUDE +=-I./include  -I$(BASE_DIR)/common/include

# Library filenames, _MT for multi-threaded version
LIBNAME=trie_node


include $(BASE_DIR)/build/Makefile.inc
