BASE_DIR=../../..

# Include files
INCLUDE +=-I./include -I../node/include -I$(BASE_DIR)/common

# Library filenames, _MT for multi-threaded version
LIBNAME=sll
LIBNAME_MT=sll_mt


include $(BASE_DIR)/build/Makefile.inc
