BASE_DIR=..

SUBDIRS = array
SUBDIRS+= bst
SUBDIRS+= heap
SUBDIRS+= sll
SUBDIRS+= trie
# SUBDIRS+= table_doubler
# SUBDIRS+= tree_heap
# SUBDIRS+= hash_tables
# SUBDIRS+= fenwick_tree

include $(BASE_DIR)/build/Makefile.inc
