BASE_DIR=../../..

# Include files
INCLUDE +=-I./include  -I$(BASE_DIR)/common/include

# Library filenames, _MT for multi-threaded version
LIBNAME=bst_node
LIBNAME_MT=bst_node_mt


include $(BASE_DIR)/build/Makefile.inc
