BASE_DIR=../../..

SUBDIRS = testcases

# Include files
INCLUDE +=-I./include  -I$(BASE_DIR)/common/include

# Library filenames, _MT for multi-threaded version
LIBNAME=bst_node


include $(BASE_DIR)/build/Makefile.inc
