LIBNAME = common
TESTDIR = tests

INCLUDE = -I$(PWD)
LIBS = -L$(OUTDIR) -lcommon

SRC = common.c
SRC += rudimentary_mem_manager.c

TESTDIR = testcases
TEST_SRC = testCommon.c

include ../build/GlobalMake
