BASE_DIR=../..

# Include files
INCLUDE +=-I./include -I$(BASE_DIR)/common/include

# Library filenames, _MT for multi-threaded version
LIBNAME=trie
#LIBNAME_MT=array_queue_mt

TEST_SUBDIRS = testcases #testcases_mt

include $(BASE_DIR)/build/Makefile.inc
