BASE_DIR=../../..

TEST_SUBDIRS = testcases

# Include files
INCLUDE +=-I./include  -I$(BASE_DIR)/common/include

# Library filenames, _MT for multi-threaded version
LIBNAME=poll_timer
LIBNAME_MT=poll_timer_mt


include $(BASE_DIR)/build/Makefile.inc
