BASE_DIR=../../..
CBASE_DIR=$(BASE_DIR)/../c/

TEST_SUBDIRS = testcases 

# Include files
INCLUDE +=-I./include #-I$(BASE_DIR)/../common/include
INCLUDE += -I$(CBASE_DIR)/Data_Structures/sll/node/include/

# Library filenames, _MT for multi-threaded version
LIBNAME=sll_node+


include $(BASE_DIR)/build/Makefile.inc
