BASE_DIR=../../..

SUBDIRS = testcases

# Include files
INCLUDE +=-I./include -I../node/include -I$(BASE_DIR)/common/include

# Library filenames, _MT for multi-threaded version
LIBNAME=bst
LIBNAME_MT=bst_mt


include $(BASE_DIR)/build/Makefile.inc
