BASE_DIR=../../

# Include files
INCLUDE +=-I./include -I$(BASE_DIR)/common/include

# Library filenames, _MT for multi-threaded version
LIBNAME=array_queue
LIBNAME_MT=array_queue_mt

SUBDIRS = testcases

include $(BASE_DIR)/build/Makefile.inc
